application: 2ndmarketplace
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:


- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /
  script: front.app

# All other pages require login
- url: /.*
  script: marketplace.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: latest